SKILLS = [
    "python",
    "java",
    "c++",
    "c",
    "javascript",
    "typescript",
    "react",
    "next.js",
    "node.js",
    "express",
    "fastapi",
    "django",
    "flask",
    "html",
    "css",
    "tailwind",
    "bootstrap",
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "redis",
    "firebase",
    "machine learning",
    "deep learning",
    "nlp",
    "computer vision",
    "data analysis",
    "data visualization",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "pytorch",
    "llm",
    "rag",
    "generative ai",
    "aws",
    "azure",
    "gcp",
    "docker",
    "kubernetes",
    "linux",
    "git",
    "github",
    "rest api",
    "graphql",
    "microservices",
    "data structures",
    "algorithms",
    "oops",
    "operating systems",
    "dbms",
    "computer networks",
    "cybersecurity",
    "network security",
    "jwt",
    "oauth",
    "testing",
    "ci/cd",
    "devops",
    "system design",
]


ALIASES = {
    "js": "javascript",
    "ts": "typescript",
    "reactjs": "react",
    "nodejs": "node.js",
    "postgres": "postgresql",
    "mongo": "mongodb",
    "ml": "machine learning",
    "dl": "deep learning",
    "natural language processing": "nlp",
    "large language model": "llm",
    "retrieval augmented generation": "rag",
    "object oriented programming": "oops",
    "object-oriented programming": "oops",
    "database management system": "dbms",
    "continuous integration": "ci/cd",
    "continuous deployment": "ci/cd",
}
